# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: caroline@springboarddesigns.co.uk
title: Springboard Designs
description: "????"
include: ['_redirects']
exclude: ['README.md']

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
# theme: minima
sass:
  style: compressed

gems: 
  - jekyll-assets
  - jekyll-seo-tag
  - jekyll-coffeescript

autowrite: true

assets:
  sources:
    - _assets/
    - _assets/css/
    - _assets/css/bootstrap/
    - _assets/css/template/
    - _assets/images/
    # - _assets/images/backgrounds/
    # - _assets/images/icons/sided-services/
    # - _assets/images/icons/
    # - _assets/images/layout/
    # - _assets/images/vector/
    - _assets/js/
    - _assets/js/jednotka/
    - _assets/js/jednotka/bootstrap/
    - _assets/js/jednotka/ie/
    - _assets/js/jednotka/jquery/
    - _assets/js/jednotka/plugins/
    - _assets/fonts/
    - _assets/fonts/font-awesome/
  digest: true        
  compress:
    css: true
    js: true

anenta: 
  company_name: Springboard Designs Ltd
  web_address: https://www.springboarddesigns.co.uk
  int_telephone: +44 (0)20 8355 0202
  telephone: 020 8355 0202
  address: ["44 Franche Court Road", "London", "SW17 0JU"]
