- name: 'Design'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

- name: 'Account Management'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

- name: 'Logistics'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

- name: 'Product Testing'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

- name: 'Ethical Trading'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

- name: 'Warehousing'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

- name: 'Consultancy'
  content: <p>Springboard specializes in designing, sourcing and delivering creative promotional and retail merchandise, print and packaging, for consumer sales and marketing activity.</p>
  image: 'images/services/design.jpg'

