- name: Account Management
  content: <p>We find merchandise solutions that reflects your brand, make it stand out against the competition, engage your customer and retain them. Working as an extension of your team, with a personal and friendly service.</p>
  image: images/services/1.jpg

- name: Creative Design Services
  content: <p>Creativity is key. We take product ideas and make them a reality - creating a sketch or a quick prototype; sometimes there’s nothing like seeing a physical sample. The item needs to capture the essence of your brand and engage your target market whilst optimising budgets. We continually monitor trends to keep ideas up to date ensuring the product is aesthetically consistent with the range for which it is intended. All items designed in house.</p>
  image: images/services/2.jpg

- name: Quality Assurance & Ethical trading
  content: '
  <p>All factories are audited annually as standard. We’ve worked with many of our factories for over 10 years. We only use factories accredited with ISO 9001 Quality Assurance and SA 8000 Environmental Assurance. We undertake During Production Inspections (DUPROs) and Final Random Inspections (FRIs) to agreed AQL levels. Our partners in this area are SGS and Intertek.</p>
  <ul>
    <li>ISO 9001 Quality Assurance</li>
    <li>SA 8000 Environmental Assurance</li>
    <li>Member of the BPMA</li>
  </ul>
  '
  image: images/services/4.jpg

- name: Logistics
  content: '
    <p>We offer a door to door service and search best prices at the time your goods are ready. Shipping documents, duty & customs clearance are all taken care of.</p>
    <ul>
      <li>Sea, Air, Road & rail transportation</li>
      <li>Best price at time of departure</li>
      <li>Overseas customs clearance</li>
      <li>Door to door delivery</li>
    </ul>
  '
  image: images/services/3.jpg


- name: Fulfilment
  content: '
    <p>Our warehouse in Ipswich is a 40,000 sq ft facility where we offer a fulfilment service and storage facilities. With a fully Customs Bonded and E.R.T.S. approved facility we can cater for all your requirements.</p>
    <ul>
      <li>Customs bonded</li>
      <li>ERTS approved for import consolidation</li>
      <li>EDI stock information system</li>
      <li>Bar code scanning</li>
      <li>Pick and pack facilities</li>
    </ul>
  '
  image: images/services/6.jpg
