- name: Account Management
  content: <p>Working as an extension of your team, with a personal and friendly service, finding solutions together. We work with you to find merchandise solutions that reflect your brand and make it stand out against the competition.</p>
  image: images/services/1.jpg

- name: Creative Design Services
  content: <p>We understand the item needs to capture the essence of your brand and engage your target market whilst optimising budgets. We continually monitor trends ensuring the product is aesthetically consistent with the range for which it is intended. All items designed in house.</p>
  image: images/services/2.jpg

- name: Quality Assurance & Ethical trading
  content: <p>We’ve worked with many of our factories for over 10 years and audit them annually. They have to be accredited with ISO 9001 Quality Assurance and SA 8000 Environmental Assurance. We undertake Production Inspections to agreed AQL levels. Our partners in this area are SGS and Intertek.</p>

  image: images/services/4.jpg

- name: Logistics
  content: '
    <p>We offer a door to door service and search best prices at the time your goods are ready. Shipping documents, duty & customs clearance are all taken care of.</p>
    <ul>
      <li>Sea, Air, Road & rail transportation</li>
      <li>Best price at time of departure</li>
      <li>Overseas customs clearance</li>
      <li>Door to door delivery</li>
    </ul>'
  image: images/services/3.jpg


- name: Fulfilment
  content: '
    <p>Our warehouse in Ipswich is a 40,000 sq ft facility where we offer a fulfilment service and storage facilities. With a fully Customs Bonded and E.R.T.S. approved facility we can cater for all your requirements.</p>
    <ul>
      <li>Customs bonded</li>
      <li>ERTS approved for import consolidation</li>
      <li>EDI stock information system</li>
      <li>Pick and pack facilities</li>
    </ul>
  '
  image: images/services/6.jpg
